version: "3.9"

services:

  insight:
    image: redislabs/redisinsight
    volumes:
      - ./data/insight:/db
    ports:
      - 8001:8001
      
  redismod:
    image: redislabs/redismod:latest
    volumes:
      - ./data/database:/data
    ports:
      - 6379:6379